name: maitreya-haskell-core
version: 0.1.0.0
description: "MAITREYA DAW - Haskell Functional Core"
license: Unlicense
author: "b122m faeb"
maintainer: "b122m@faeb.com"
copyright: "2024 b122m faeb"

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.14 && < 5
- containers
- vector
- bytestring
- text
- aeson
- time
- random
- mtl

library:
  source-dirs: src
  exposed-modules:
    - Maîtreya.Core
    - Maîtreya.Audio.Engine
    - Maîtreya.SIEGE.Expressions
    - Maîtreya.URSA.Assembly

executables:
  maitreya-haskell:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  maitreya-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hspec
    - QuickCheck
